cache:
  paths:
    - node_modules/

stages:
  - dev
  - build

before_script:
  - npm install -d --registry=https://registry.npm.taobao.org

dev_compile:
  stage: dev
  tags: dev
  only:
    - /^dev\/.*$/
  script:
    - npm run dev

build:
  stage: build
  tags: build
  only:
    - /^build\/.*$/
  script:
    - npm run build
